name: qalbcare
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  flutter_card_swiper: ^7.0.2
  cupertino_icons: ^1.0.8
  webview_flutter: ^4.2.2
  cloud_firestore: ^5.6.11
  firebase_database: ^11.3.9
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  liquid_swipe: ^3.1.0
  flutter_svg: ^2.0.10+1
  flutter_dotenv: ^5.1.0
  awesome_notifications: ^0.10.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
    - assets/.env
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
